
/// @file parse_library.cc
/// @brief parse_library() の実装ファイル
/// @author Yusuke Matsunaga (松永 裕介)
///
/// Copyright (C) 2005-2011, 2014, 2018, 2021 Yusuke Matsunaga
/// All rights reserved.

#include "dotlib/Parser.h"
#include "dotlib/AstAttr.h"


BEGIN_NAMESPACE_YM_DOTLIB

// @brief 'library' group statement のパースを行う．
AstAttrPtr
parse_library(Parser& parser,
	      const AttrKwd& attr)
{
  static AttrHandlerDict handler_dict{
    // simple attributes
    { AttrType::bus_naming_style,               parse_string },
    { AttrType::comment,                        parse_string },
    { AttrType::current_unit,                   parse_string },
    { AttrType::date,                           parse_string },
    { AttrType::delay_model,                    parse_delay_model },
    { AttrType::em_temp_degradation_factor,     parse_float },
    { AttrType::fall_net_delay,                 parse_string },
    { AttrType::fpga_domain_style,              parse_string },
    { AttrType::fpga_technology,                parse_string },
    { AttrType::in_place_swap_mode,             parse_string },
    { AttrType::input_threshold_pct_fall,       parse_float },
    { AttrType::input_threshold_pct_rise,       parse_float },
    { AttrType::leakage_power_unit,             parse_string },
    { AttrType::nom_calc_mode,                  parse_string },
    { AttrType::nom_process,                    parse_float },
    { AttrType::nom_temperature,                parse_float },
    { AttrType::nom_voltage,                    parse_float },
    { AttrType::output_threshold_pct_fall,      parse_float },
    { AttrType::output_threshold_pct_rise,      parse_float },
    { AttrType::piece_type,                     parse_string },
    { AttrType::power_model,                    parse_string },
    { AttrType::power_unit,                     parse_string },
    { AttrType::preferred_input_pad_voltage,    parse_string },
    { AttrType::preferred_output_pad_slew_rate_control, parse_string },
    { AttrType::preferred_output_pad_voltage,   parse_string },
    { AttrType::pulling_resistance_unit,        parse_string },
    { AttrType::rise_net_delay,                 parse_string },
    { AttrType::resistance_unit,                parse_string },
    { AttrType::revision,                       parse_string },
    { AttrType::simulation,                     parse_bool },
    { AttrType::slew_derate_from_library,       parse_float },
    { AttrType::slew_lower_threshold_pct_fall,  parse_float },
    { AttrType::slew_lower_threshold_pct_rise,  parse_float },
    { AttrType::slew_upper_threshold_pct_fall,  parse_float },
    { AttrType::slew_upper_threshold_pct_rise,  parse_float },
    { AttrType::threshold_voltage_group,        parse_string },
    { AttrType::time_unit,                      parse_string },
    { AttrType::voltage_unit,                   parse_string },

    { AttrType::default_cell_leakage_power,     parse_float },
    { AttrType::default_connection_class,       parse_string },
    { AttrType::default_fall_delay_intercept,   parse_float },
    { AttrType::default_fall_pin_resistance,    parse_float },
    { AttrType::default_fanout_load,            parse_float },
    { AttrType::default_fpga_isd,               parse_string },
    { AttrType::default_inout_pin_cap,          parse_float },
    { AttrType::default_inout_pin_fall_res,     parse_float },
    { AttrType::default_inout_pin_rise_res,     parse_float },
    { AttrType::default_input_pin_cap,          parse_float },
    { AttrType::default_input_pin_fall_res,     parse_float },
    { AttrType::default_input_pin_rise_res,     parse_float },
    { AttrType::default_intrinsic_fall,         parse_float },
    { AttrType::default_intrinsic_rise,         parse_float },
    { AttrType::default_leakage_power_density,  parse_float },
    { AttrType::default_max_capacitance,        parse_float },
    { AttrType::default_max_fanout,             parse_float },
    { AttrType::default_max_transition,         parse_float },
    { AttrType::default_min_porosity,           parse_float },
    { AttrType::default_operating_conditions,   parse_string },
    { AttrType::default_output_pin_cap,         parse_float },
    { AttrType::default_output_pin_fall_res,    parse_float },
    { AttrType::default_output_pin_rise_res,    parse_float },
    { AttrType::default_rise_delay_intercept,   parse_float },
    { AttrType::default_rise_pin_resistance,    parse_float },
    { AttrType::default_slope_fall,             parse_float },
    { AttrType::default_slope_rise,             parse_float },
    { AttrType::default_wire_load,              parse_string },
    { AttrType::default_wire_load_area,         parse_float },
    { AttrType::default_wire_load_capacitance,  parse_float },
    { AttrType::default_wire_load_mode,         parse_string },
    { AttrType::default_wire_load_selection,    parse_string },

    { AttrType::k_process_cell_fall,            parse_float },
    { AttrType::k_process_cell_leakage_power,   parse_float },
    { AttrType::k_process_cell_rise,            parse_float },
    { AttrType::k_process_drive_current,        parse_float },
    { AttrType::k_process_drive_fall,           parse_float },
    { AttrType::k_process_drive_rise,           parse_float },
    { AttrType::k_process_fall_delay_intercept, parse_float },
    { AttrType::k_process_fall_pin_resistance,  parse_float },
    { AttrType::k_process_fall_propagation,     parse_float },
    { AttrType::k_process_fall_transition,      parse_float },
    { AttrType::k_process_hold_fall,            parse_float },
    { AttrType::k_process_hold_rise,            parse_float },
    { AttrType::k_process_internal_power,       parse_float },
    { AttrType::k_process_intrinsic_fall,       parse_float },
    { AttrType::k_process_intrinsic_rise,       parse_float },
    { AttrType::k_process_min_period,           parse_float },
    { AttrType::k_process_min_pulse_width_high, parse_float },
    { AttrType::k_process_min_pulse_width_low,  parse_float },
    { AttrType::k_process_nochange_fall,        parse_float },
    { AttrType::k_process_nochange_rise,        parse_float },
    { AttrType::k_process_pin_cap,              parse_float },
    { AttrType::k_process_recovery_fall,        parse_float },
    { AttrType::k_process_recovery_rise,        parse_float },
    { AttrType::k_process_removal_fall,         parse_float },
    { AttrType::k_process_removal_rise,         parse_float },
    { AttrType::k_process_rise_delay_intercept, parse_float },
    { AttrType::k_process_rise_pin_resistance,  parse_float },
    { AttrType::k_process_rise_propagation,     parse_float },
    { AttrType::k_process_rise_transition,      parse_float },
    { AttrType::k_process_setup_fall,           parse_float },
    { AttrType::k_process_setup_rise,           parse_float },
    { AttrType::k_process_skew_fall,            parse_float },
    { AttrType::k_process_skew_rise,            parse_float },
    { AttrType::k_process_slope_fall,           parse_float },
    { AttrType::k_process_slope_rise,           parse_float },
    { AttrType::k_process_wire_cap,             parse_float },
    { AttrType::k_process_wire_res,             parse_float },

    { AttrType::k_temp_cell_fall,            parse_float },
    { AttrType::k_temp_cell_leakage_power,   parse_float },
    { AttrType::k_temp_cell_rise,            parse_float },
    { AttrType::k_temp_drive_current,        parse_float },
    { AttrType::k_temp_drive_fall,           parse_float },
    { AttrType::k_temp_drive_rise,           parse_float },
    { AttrType::k_temp_fall_delay_intercept, parse_float },
    { AttrType::k_temp_fall_pin_resistance,  parse_float },
    { AttrType::k_temp_fall_propagation,     parse_float },
    { AttrType::k_temp_fall_transition,      parse_float },
    { AttrType::k_temp_hold_fall,            parse_float },
    { AttrType::k_temp_hold_rise,            parse_float },
    { AttrType::k_temp_internal_power,       parse_float },
    { AttrType::k_temp_intrinsic_fall,       parse_float },
    { AttrType::k_temp_intrinsic_rise,       parse_float },
    { AttrType::k_temp_min_period,           parse_float },
    { AttrType::k_temp_min_pulse_width_high, parse_float },
    { AttrType::k_temp_min_pulse_width_low,  parse_float },
    { AttrType::k_temp_nochange_fall,        parse_float },
    { AttrType::k_temp_nochange_rise,        parse_float },
    { AttrType::k_temp_pin_cap,              parse_float },
    { AttrType::k_temp_recovery_fall,        parse_float },
    { AttrType::k_temp_recovery_rise,        parse_float },
    { AttrType::k_temp_removal_fall,         parse_float },
    { AttrType::k_temp_removal_rise,         parse_float },
    { AttrType::k_temp_rise_delay_intercept, parse_float },
    { AttrType::k_temp_rise_pin_resistance,  parse_float },
    { AttrType::k_temp_rise_propagation,     parse_float },
    { AttrType::k_temp_rise_transition,      parse_float },
    { AttrType::k_temp_setup_fall,           parse_float },
    { AttrType::k_temp_setup_rise,           parse_float },
    { AttrType::k_temp_skew_fall,            parse_float },
    { AttrType::k_temp_skew_rise,            parse_float },
    { AttrType::k_temp_slope_fall,           parse_float },
    { AttrType::k_temp_slope_rise,           parse_float },
    { AttrType::k_temp_wire_cap,             parse_float },
    { AttrType::k_temp_wire_res,             parse_float },

    { AttrType::k_volt_cell_fall,            parse_float },
    { AttrType::k_volt_cell_leakage_power,   parse_float },
    { AttrType::k_volt_cell_rise,            parse_float },
    { AttrType::k_volt_drive_current,        parse_float },
    { AttrType::k_volt_drive_fall,           parse_float },
    { AttrType::k_volt_drive_rise,           parse_float },
    { AttrType::k_volt_fall_delay_intercept, parse_float },
    { AttrType::k_volt_fall_pin_resistance,  parse_float },
    { AttrType::k_volt_fall_propagation,     parse_float },
    { AttrType::k_volt_fall_transition,      parse_float },
    { AttrType::k_volt_hold_fall,            parse_float },
    { AttrType::k_volt_hold_rise,            parse_float },
    { AttrType::k_volt_internal_power,       parse_float },
    { AttrType::k_volt_intrinsic_fall,       parse_float },
    { AttrType::k_volt_intrinsic_rise,       parse_float },
    { AttrType::k_volt_min_period,           parse_float },
    { AttrType::k_volt_min_pulse_width_high, parse_float },
    { AttrType::k_volt_min_pulse_width_low,  parse_float },
    { AttrType::k_volt_nochange_fall,        parse_float },
    { AttrType::k_volt_nochange_rise,        parse_float },
    { AttrType::k_volt_pin_cap,              parse_float },
    { AttrType::k_volt_recovery_fall,        parse_float },
    { AttrType::k_volt_recovery_rise,        parse_float },
    { AttrType::k_volt_removal_fall,         parse_float },
    { AttrType::k_volt_removal_rise,         parse_float },
    { AttrType::k_volt_rise_delay_intercept, parse_float },
    { AttrType::k_volt_rise_pin_resistance,  parse_float },
    { AttrType::k_volt_rise_propagation,     parse_float },
    { AttrType::k_volt_rise_transition,      parse_float },
    { AttrType::k_volt_setup_fall,           parse_float },
    { AttrType::k_volt_setup_rise,           parse_float },
    { AttrType::k_volt_skew_fall,            parse_float },
    { AttrType::k_volt_skew_rise,            parse_float },
    { AttrType::k_volt_slope_fall,           parse_float },
    { AttrType::k_volt_slope_rise,           parse_float },
    { AttrType::k_volt_wire_cap,             parse_float },
    { AttrType::k_volt_wire_res,             parse_float },

    // complex attributes
    { AttrType::capacitive_load_unit,           parse_float_string },
    { AttrType::default_part,                   parse_string_string },
    { AttrType::define,                         parse_define },
    { AttrType::define_cell_area,               parse_string_string },
    { AttrType::define_group,                   parse_string_string },
    { AttrType::library_features,               parse_string_list },
    { AttrType::piece_define,                   parse_string_complex },
    { AttrType::routing_layers,                 parse_string_list },
    { AttrType::technology,                     parse_technology },

    // group statements
    { AttrType::cell,                           parse_cell },
    { AttrType::dc_current_template,            parse_template },
    { AttrType::em_lut_template,                parse_template },
    { AttrType::fall_transition_degradation,    parse_degradation },
    { AttrType::faults_lut_template,            parse_template },
    { AttrType::input_voltage,                  parse_input_voltage },
    { AttrType::iv_lut_template,                parse_template },
    { AttrType::lu_table_template,              parse_template },
    { AttrType::noise_lut_template,             parse_template },
    { AttrType::operating_conditions,           parse_operating_conditions },
    { AttrType::output_voltage,                 parse_output_voltage },
    { AttrType::part,                           parse_part },
    { AttrType::poly_template,                  parse_template },
    { AttrType::power_lut_template,             parse_template },
    { AttrType::power_poly_template,            parse_template },
    { AttrType::power_supply,                   parse_power_supply },
    { AttrType::propagation_lut_template,       parse_template },
    { AttrType::rise_transition_degradation,    parse_degradation },
    { AttrType::scaled_cell,                    parse_cell },
    { AttrType::scaling_factors,                parse_scaling_factors },
    { AttrType::timing,                         parse_timing },
    { AttrType::timing_range,                   parse_timing_range },
    { AttrType::type,                           parse_type },
    { AttrType::wire_load,                      parse_wire_load },
    { AttrType::wire_load_selection,            parse_wire_load_selection },
    { AttrType::wire_load_table,                parse_wire_load_table }
  };
  return parser.parse_group_statement(attr, Parser::sStrHeader, handler_dict);
}

END_NAMESPACE_YM_DOTLIB
